
// This file is automatically generated. Do not edit it directly.
import supabase from '@/lib/supabaseInit';
import type { Database } from './types';

// Export the singleton instance
export { supabase };
